version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - HATHIFILES_MYSQL_CONNECTION=mysql2://root:pass@database/hathifiles

  database:
    build: dev_db/.

volumes:
  gem_cache:
