services:
  test:
    build: .
    environment:
      # Used by dumper.rb
      HATHIFILES_MYSQL_USER: "ht_rights"
      HATHIFILES_MYSQL_PASSWORD: "ht_rights"
      HATHIFILES_MYSQL_HOST: "mariadb"
      HATHIFILES_MYSQL_DATABASE: "ht"
      # Used by connection.rb
      # TODO: construct this based on the above variables
      HATHIFILES_MYSQL_CONNECTION: "mysql2://ht_rights:ht_rights@mariadb/ht"
      HATHIFILES_DIR: "/usr/src/app/spec/data"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bash -c "/usr/local/bin/wait-for mariadb:3306 && bundle exec rspec"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    #volumes:
    #  - ./sql/100_rights_log.sql:/docker-entrypoint-initdb.d/100_rights_log.sql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights


volumes:
  gem_cache:

